using InsertProductsFromExcelFiles.AppModels;
using InsertProductsFromExcelFiles.BiggBrands;
using System;
using System.Collections.Generic;
using System.Text;

namespace InsertProductsFromExcelFiles.Utils
{
    public static class ExcelProductUtil
    {
        public static List<SpecificationAttributeOptionCustomValueMap> GenerateAllSpecificationAttributeOptionListForExcelProduct(ExcelProduct excelProduct)
        {
            List<SpecificationAttributeOptionCustomValueMap> specificationAttributeOptionCustomValueMapList = new List<SpecificationAttributeOptionCustomValueMap>
            {
                
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Season Code"                         ,excelProduct.SeasonCode                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Year"                                ,excelProduct.Year                               ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Style or Part Number"                ,excelProduct.StyleorPartNumber                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Brand Name"                          ,excelProduct.BrandName                          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Department"                          ,excelProduct.Department                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Type"                        ,excelProduct.ProductType                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Subtype"                     ,excelProduct.ProductSubtype                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Sport Type"                          ,excelProduct.SportType                          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Country of Origin"                   ,excelProduct.CountryofOrigin                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Style or Part Name"                  ,excelProduct.StyleorPartName                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Colour Name"                         ,excelProduct.ColourName                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Colour Family"                       ,excelProduct.ColourFamily                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Size"                                ,excelProduct.Size                               ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Sizing Standard"                     ,excelProduct.SizingStandard                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Target Age Range"                    ,excelProduct.TargetAgeRange                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Special Size Type"                   ,excelProduct.SpecialSizeType                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Material"                            ,excelProduct.Material                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Lining Material"                     ,excelProduct.LiningMaterial                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Neckline"                            ,excelProduct.Neckline                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Sleeve Type"                         ,excelProduct.SleeveType                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Fit"                                 ,excelProduct.Fit                                ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Occasion"                            ,excelProduct.Occasion                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Skirt/Dress Length"                  ,excelProduct.SkirtDressLength                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Waist Type"                          ,excelProduct.WaistType                          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Bra Support"                         ,excelProduct.BraSupport                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Care Instructions"                   ,excelProduct.CareInstructions                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Key 1"                     ,excelProduct.AttributeKey1                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Value 1"                   ,excelProduct.AttributeValue1                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Key 2"                     ,excelProduct.AttributeKey2                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Value 2"                   ,excelProduct.AttributeValue2                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Key 3"                     ,excelProduct.AttributeKey3                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Value 3"                   ,excelProduct.AttributeValue3                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Key 4"                     ,excelProduct.AttributeKey4                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Value 4"                   ,excelProduct.AttributeValue4                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Key 5"                     ,excelProduct.AttributeKey5                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Attribute Value 5"                   ,excelProduct.AttributeValue5                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Shipping Length (cm)"                ,excelProduct.ShippingLengthcm                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Shipping Height (cm)"                ,excelProduct.ShippingHeightcm                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Shipping Width/Depth (cm)"           ,excelProduct.ShippingWidthDepthcm               ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Shipping Weight (KG)"                ,excelProduct.ShippingWeightKG                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Shipping Destination"                ,excelProduct.ShippingDestination                ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Quantity/Stock"                      ,excelProduct.QuantityStock                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Fulfilment Method"                   ,excelProduct.FulfilmentMethod                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Processing Time"                     ,excelProduct.ProcessingTime                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("MSRP AE"                             ,excelProduct.MSRPAE                             ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("MSRP SA"                             ,excelProduct.MSRPSA                             ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("MSRP EG"                             ,excelProduct.MSRPEG                             ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Cost (AED)"                          ,excelProduct.CostAED                            ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Selling Price (AED)"                 ,excelProduct.SellingPriceAED                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Selling Price (SAR)"                 ,excelProduct.SellingPriceSAR                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Selling Price (EGP)"                 ,excelProduct.SellingPriceEGP                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Promotional Price (AED)"             ,excelProduct.PromotionalPriceAED                ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Promotional Price (SAR)"             ,excelProduct.PromotionalPriceSAR                ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Promotional Price (EGP)"             ,excelProduct.PromotionalPriceEGP                ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("HS Code"                             ,excelProduct.HSCode                             ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Model Number"                        ,excelProduct.ModelNumber                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Model Name"                          ,excelProduct.ModelName                          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Length"                      ,excelProduct.ProductLength                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Length Unit"                         ,excelProduct.LengthUnit                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Height"                      ,excelProduct.ProductHeight                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Height Unit"                         ,excelProduct.HeightUnit                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Width/Depth"                 ,excelProduct.ProductWidthDepth                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Width/Depth Unit"                    ,excelProduct.WidthDepthUnit                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Weight"                      ,excelProduct.ProductWeight                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Weight Unit"                         ,excelProduct.WeightUnit                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Capacity"                            ,excelProduct.Capacity                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Capacity Unit"                       ,excelProduct.CapacityUnit                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Number of Pieces"                    ,excelProduct.NumberofPieces                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Size Unit"                           ,excelProduct.SizeUnit                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Exterior Material"                   ,excelProduct.ExteriorMaterial                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Interior Material"                   ,excelProduct.InteriorMaterial                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Strap Material"                      ,excelProduct.StrapMaterial                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Compatible With"                     ,excelProduct.CompatibleWith                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Base Material"                       ,excelProduct.BaseMaterial                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Secondary Material"                  ,excelProduct.SecondaryMaterial                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Material Finish"                     ,excelProduct.MaterialFinish                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Types of Shower Head"                ,excelProduct.TypesofShowerHead                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Types of Dispenser"                  ,excelProduct.TypesofDispenser                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Number of Spray Settings"            ,excelProduct.NumberofSpraySettings              ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Assembly Required"                   ,excelProduct.AssemblyRequired                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Set Includes"                        ,excelProduct.SetIncludes                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Filling Material"                    ,excelProduct.FillingMaterial                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Comfort Level"                       ,excelProduct.ComfortLevel                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Sheet Type"                          ,excelProduct.SheetType                          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Pack Size"                           ,excelProduct.PackSize                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Formation"                           ,excelProduct.Formation                          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Target Use/Application"              ,excelProduct.TargetUseApplication               ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Target Skin Type"                    ,excelProduct.TargetSkinType                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("UV Protection"                       ,excelProduct.UVProtection                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Battery Size"                        ,excelProduct.BatterySize                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Battery Size Unit"                   ,excelProduct.BatterySizeUnit                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Brand Compatibility"                 ,excelProduct.BrandCompatibility                 ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Connection Type"                     ,excelProduct.ConnectionType                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Case Type"                           ,excelProduct.CaseType                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Charging Type"                       ,excelProduct.ChargingType                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Phone Case Material"                 ,excelProduct.PhoneCaseMaterial                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Audio Headphone Type"                ,excelProduct.AudioHeadphoneType                 ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Warranty Years"                      ,excelProduct.WarrantyYears                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Frame Colour"                        ,excelProduct.FrameColour                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Frame Colour Family"                 ,excelProduct.FrameColourFamily                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Lens Colour"                         ,excelProduct.LensColour                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Lens Colour Family"                  ,excelProduct.LensColourFamily                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Frame Shape/Style"                   ,excelProduct.FrameShapeStyle                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Lens Focal Type"                     ,excelProduct.LensFocalType                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Lens Magnification"                  ,excelProduct.LensMagnification                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Lens Type"                           ,excelProduct.LensType                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Width Profile"                       ,excelProduct.WidthProfile                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Upper Material"                      ,excelProduct.UpperMaterial                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Sole Material"                       ,excelProduct.SoleMaterial                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Heel Type"                           ,excelProduct.HeelType                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Heel Profile"                        ,excelProduct.HeelProfile                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Heel Height"                         ,excelProduct.HeelHeight                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Heel Height Unit"                    ,excelProduct.HeelHeightUnit                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Boot Shaft Height"                   ,excelProduct.BootShaftHeight                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Boot Shaft Height Unit"              ,excelProduct.BootShaftHeightUnit                ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Boot Circumference"                  ,excelProduct.BootCircumference                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Boot Circumference Unit"             ,excelProduct.BootCircumferenceUnit              ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Closure/Fastener"                    ,excelProduct.ClosureFastener                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Wardrobe Design"                     ,excelProduct.WardrobeDesign                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Upholstery Type"                     ,excelProduct.UpholsteryType                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Seat Filling"                        ,excelProduct.SeatFilling                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Seat Cushion"                        ,excelProduct.SeatCushion                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Wood Type"                           ,excelProduct.WoodType                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Wood Tone"                           ,excelProduct.WoodTone                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Shape"                               ,excelProduct.Shape                              ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Number of Drawers"                   ,excelProduct.NumberofDrawers                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Number of Doors"                     ,excelProduct.NumberofDoors                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Number of Shelves"                   ,excelProduct.NumberofShelves                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Number of Seats"                     ,excelProduct.NumberofSeats                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Number of Panels"                    ,excelProduct.NumberofPanels                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Installation"                        ,excelProduct.Installation                       ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Energy Used"                         ,excelProduct.EnergyUsed                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Additional Feature 1"                ,excelProduct.AdditionalFeature1                 ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Additional Feature 2"                ,excelProduct.AdditionalFeature2                 ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Additional Feature 3"                ,excelProduct.AdditionalFeature3                 ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Pattern"                             ,excelProduct.Pattern                            ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Mats, Rugs & Carpet Design"          ,excelProduct.MatsRugsCarpetDesign               ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Technique"                           ,excelProduct.Technique                          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Style of Curtain Lining"             ,excelProduct.StyleofCurtainLining               ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Dispenser Type"                      ,excelProduct.DispenserType                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Scents/Notes"                        ,excelProduct.ScentsNotes                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Aromatherapy Type"                   ,excelProduct.AromatherapyType                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Fine/Luxury Material"                ,excelProduct.FineLuxuryMaterial                 ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Base Material Type"                  ,excelProduct.BaseMaterialType                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Stone/Gem"                           ,excelProduct.StoneGem                           ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Carat Weight"                        ,excelProduct.CaratWeight                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Closure/Fastening"                   ,excelProduct.ClosureFastening                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Features 1"                  ,excelProduct.ProductFeatures1                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Features 2"                  ,excelProduct.ProductFeatures2                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Features 3"                  ,excelProduct.ProductFeatures3                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Features 4"                  ,excelProduct.ProductFeatures4                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Product Features 5"                  ,excelProduct.ProductFeatures5                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Ink Colour Family"                   ,excelProduct.InkColourFamily                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Pen Material"                        ,excelProduct.PenMaterial                        ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Point or Nib Type"                   ,excelProduct.PointorNibType                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Point Size"                          ,excelProduct.PointSize                          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Point Size Unit"                     ,excelProduct.PointSizeUnit                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Refillable"                          ,excelProduct.Refillable                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Band Colour"                   ,excelProduct.WatchBandColour                    ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Band Colour Family"            ,excelProduct.WatchBandColourFamily              ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Band Length"                         ,excelProduct.BandLength                         ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Band Length Unit"                    ,excelProduct.BandLengthUnit                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Band Material"                 ,excelProduct.WatchBandMaterial                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Dial/Face Type"                ,excelProduct.WatchDialFaceType                  ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Dial/Face Diameter"                  ,excelProduct.DialFaceDiameter                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Dial/Face Diameter Unit"             ,excelProduct.DialFaceDiameterUnit               ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Dial/Face Colour"              ,excelProduct.WatchDialFaceColour                ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Dial/Face Colour Family"       ,excelProduct.WatchDialFaceColourFamily          ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Movement"                      ,excelProduct.WatchMovement                      ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Case Shape"                    ,excelProduct.WatchCaseShape                     ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Watch Band Closure"                  ,excelProduct.WatchBandClosure                   ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Interchangeable Dial/Face"           ,excelProduct.InterchangeableDialFace            ),
                SpecificationAttributeOptionUtil.FindSpecificationAttributeOptionWithCustomValue("Interchangeable Strap"               ,excelProduct.InterchangeableStrap               ),
            };

            return specificationAttributeOptionCustomValueMapList;
        }
    }
}
